#!/bin/sh
# The same sandbox around the argparse version, to see what the kit makes of it
here="$(cd "$(dirname "$0")" && pwd)"
mkdir -p "$here/.sandbox"
HOME="$here/.sandbox" exec "$here/../../../.venv/bin/python" "$here/../todo_argparse.py" "$@"
