"""Shell completion generated from the manifest: the ``completion`` built-in"""

import io
import json
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import pytest
from conftest import WINDOWS

from treaty import App, Arg, Ctx, Flag, NoArgs
from treaty._tools import tool_entries

BASH = shutil.which("bash")
ZSH = shutil.which("zsh")
needs_bash = pytest.mark.skipif(WINDOWS or BASH is None, reason="needs a POSIX bash")
needs_zsh = pytest.mark.skipif(WINDOWS or ZSH is None, reason="needs zsh")


@dataclass(frozen=True, slots=True)
class AddArgs:
    name: Literal["base coat", "it's", "top"] = Arg(description="Layer to add")
    mode: Literal["fast", "slow"] = Flag(default="fast", short="m", description="How")
    src: Path | None = Flag(default=None, description="Image to start from")


@dataclass(frozen=True, slots=True)
class RunArgs:
    target: Path = Arg(description="Script to run")
    rest: tuple[str, ...] | None = Arg(description="Passed to the script verbatim")
    loud: bool = Flag(default=False, description="Say more")


def paint() -> App:
    app = App("paint", version="2.1.0")
    layer = app.group("canvas", description="Work on the canvas").group(
        "layer", description="Stack layers"
    )

    @layer.command("add", description="Add a layer", danger_level="safe", exit_codes=())
    def add(args: AddArgs, ctx: Ctx) -> dict[str, str]:
        return {"name": args.name}

    @app.command(
        "run",
        description="Run a script",
        danger_level="safe",
        exit_codes=(),
        option_placement="strict",
    )
    def run_(args: RunArgs, ctx: Ctx) -> dict[str, str]:
        return {"target": str(args.target)}

    return app


def call(app: App, argv: list[str]) -> tuple[int, str]:
    out = io.StringIO()
    code = app.run(argv, stdin=io.StringIO(), stdout=out, stderr=io.StringIO(), env={})
    return code, out.getvalue()


def script(shell: str) -> str:
    code, text = call(paint(), ["completion", shell, "--format", "plain"])
    assert code == 0, text
    return text


def test_json_carries_the_script_and_plain_prints_it_alone() -> None:
    code, text = call(paint(), ["completion", "bash", "--format", "json"])
    assert code == 0
    data = json.loads(text)["data"]
    assert data["shell"] == "bash"
    assert data["script"] == script("bash")
    assert script("bash").startswith("# bash completion for paint 2.1.0, generated by treaty")
    assert script("zsh").startswith("#compdef paint\n")
    assert "complete -F _paint_complete paint\n" in script("bash")


def test_an_unknown_shell_is_an_argument_error() -> None:
    code, text = call(paint(), ["completion", "tcsh", "--format", "json"])
    assert code == 2
    assert "bash" in text and "zsh" in text


def test_the_manifest_lists_it_as_a_safe_built_in() -> None:
    app = paint()
    entry = app.manifest()["commands"]["completion"]
    assert entry["danger_level"] == "safe"
    assert entry["positionals"][0]["enum_values"] == ["bash", "zsh"]


def test_an_app_command_named_completion_replaces_it() -> None:
    app = App("own", version="1.0.0")

    @app.command("completion", description="Mine", danger_level="safe", exit_codes=())
    def mine(args: NoArgs, ctx: Ctx) -> dict[str, bool]:
        return {"mine": True}

    code, text = call(app, ["completion", "--format", "json"])
    assert code == 0
    assert json.loads(text)["data"] == {"mine": True}


# Each case: the words typed, the last one being completed, and the candidates offered
CASES: list[tuple[list[str], set[str]]] = [
    (["canvas", ""], {"layer"}),
    (["canvas", "layer", ""], {"add"}),
    (["canvas", "layer", "add", ""], {"base coat", "it's", "top"}),
    (["canvas", "layer", "add", "it"], {"it's"}),
    (["canvas", "layer", "add", "-m", ""], {"fast", "slow"}),
    (["canvas", "layer", "add", "--mode", "slow", ""], {"base coat", "it's", "top"}),
    (["canvas", "layer", "add", "top", ""], set()),
    (["--format", "json", "canvas", ""], {"layer"}),
    (["canvas", "layer", "add", "--src", "pi"], {"picture.png"}),
    (["run", ""], {"picture.png"}),
    (["run", "--lo"], {"--loud"}),
    (["run", "script.sh", "--lo"], set()),
    (["run", "script.sh", "x", ""], set()),
    (["--ver"], {"--verbose", "--version"}),
    (["run", "--ver"], {"--verbose"}),
    (["canvas", "layer", "add", "--format", "js"], {"json", "jsonl"}),
]


ROOT_WORDS = {"canvas", "run", "completion", "manifest", "version", "doctor", "exec"}


def workdir(tmp_path: Path) -> Path:
    """The directory completion runs in: one file, apart from the script under test"""
    work = tmp_path / "work"
    work.mkdir(exist_ok=True)
    (work / "picture.png").touch()
    return work


@needs_bash
@pytest.mark.parametrize(("typed", "expected"), CASES)
def test_bash_completes(tmp_path: Path, typed: list[str], expected: set[str]) -> None:
    assert bash_candidates(tmp_path, typed) == expected


@needs_bash
def test_bash_completes_the_root_and_a_value_after_an_equals_sign(tmp_path: Path) -> None:
    assert ROOT_WORDS <= bash_candidates(tmp_path, [""])
    # Bash 4 and later split --format=j at the =; bash 3.2 keeps it one word
    assert bash_candidates(tmp_path, ["--format", "=", "j"]) == {"json", "jsonl"}
    assert bash_candidates(tmp_path, ["--format", "="]) == set()
    assert bash_candidates(tmp_path, ["--format=j"]) == {"json", "jsonl"}


@needs_zsh
@pytest.mark.parametrize(("typed", "expected"), CASES)
def test_zsh_completes(tmp_path: Path, typed: list[str], expected: set[str]) -> None:
    assert zsh_candidates(tmp_path, typed) == expected


@needs_zsh
def test_zsh_completes_the_root_and_a_value_after_an_equals_sign(tmp_path: Path) -> None:
    assert ROOT_WORDS <= zsh_candidates(tmp_path, [""])
    assert zsh_candidates(tmp_path, ["--format=j"]) == {"json", "jsonl"}
    assert ZSH is not None
    path = tmp_path / "_paint"
    path.write_text(script("zsh"))
    assert subprocess.run([ZSH, "-n", str(path)], check=False).returncode == 0


def bash_candidates(tmp_path: Path, typed: list[str]) -> set[str]:
    assert BASH is not None
    path = tmp_path / "paint.bash"
    path.write_text(script("bash"))
    work = workdir(tmp_path)
    driver = (
        'source "$0"; COMP_WORDS=(paint "$@"); COMP_CWORD=$#; '
        'COMPREPLY=(); _paint_complete; printf "%s\\n" "${COMPREPLY[@]}"'
    )
    done = subprocess.run(
        [BASH, "--norc", "-c", driver, str(path), *typed],
        cwd=work,
        capture_output=True,
        text=True,
        check=False,
    )
    assert done.stderr == ""
    return {line for line in done.stdout.split("\n") if line}


# zsh's completion widgets only run inside the line editor, so these stand-ins print what
# each would offer and filter by the typed prefix, as zsh does
ZSH_STUBS = r"""
compdef() { :; }
prefix=
_describe() {
    local -a found
    found=("${(@P)4}")
    [[ $5 == -- ]] && found+=("${(@P)6}")
    print -rl -- ${(M)${found%%:*}:#$prefix*}
}
compadd() { shift; print -rl -- ${(M)@:#$prefix*}; }
_files() { print -rl -- $prefix*(N); }
compset() { prefix=${prefix#*=}; }
"""


def zsh_candidates(tmp_path: Path, typed: list[str]) -> set[str]:
    assert ZSH is not None
    path = tmp_path / "_paint"
    path.write_text(ZSH_STUBS + script("zsh"))
    work = workdir(tmp_path)
    driver = 'source "$1"; shift; words=(paint "$@"); CURRENT=$#words; prefix=$words[-1]; '
    driver += "_paint_complete"
    done = subprocess.run(
        [ZSH, "-f", "-c", driver, "zsh", str(path), *typed],
        cwd=work,
        capture_output=True,
        text=True,
        check=False,
    )
    assert done.stderr == ""
    return {line for line in done.stdout.split("\n") if line}


def test_mcp_serves_no_completion_tool_unless_the_app_defines_one() -> None:
    assert "completion" not in [e.name for e in tool_entries(paint())]
    app = App("own", version="1.0.0")

    @app.command("completion", description="Mine", danger_level="safe", exit_codes=())
    def mine(args: NoArgs, ctx: Ctx) -> dict[str, bool]:
        return {"mine": True}

    assert "completion" in [e.name for e in tool_entries(app)]
